SELECT ISNULL(NULL,100)
SELECT ISNULL(CAST(NULL AS INT),'HELLO')
SELECT ISNULL(CAST(NULL AS CHAR(3)),'HELLO')

SELECT COALESCE(NULL,NULL,100,NULL,50)
SELECT NULL + 1


SELECT NULLIF(1,1)
SELECT NULLIF(1,0)
SELECT NULLIF('Hello','Hello')
SELECT NULLIF('Hi','Hello')
